# Generated by Django 4.1.7 on 2023-03-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmakesapp', '0003_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
